[package]
name = "shared-clipboard-client-generic"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { version = "1.0", default-features = false }
serde = { version = "1", default-features = false, features = ["derive"] }
toml = { version = "0.8", default-features = false, features = ["parse"] }

log = { version = "0.4", default-features = false }
pretty_env_logger = { version = "0.5", default-features = false }

shared-clipboard-common = { git = "https://github.com/iliabylich/shared-clipboard-common.git" }

tokio-websockets = { version = "0.11", features = [
    "ring",
    "client",
    "fastrand",
    "native-tls",
] }
tokio-native-tls = { version = "0.3", default-features = false }
http = { version = "1.3", default-features = false }
tokio = { version = "1", default-features = false, features = [
    "time",
    "rt",
    "macros",
] }
futures-util = { version = "0.3", default-features = false, features = [
    "sink",
] }
