language = "C"
pragma_once = true
usize_is_size_t = true
style = "type"
no_includes = true
sys_includes = ["stdint.h", "stdbool.h"]

[enum]
prefix_with_name = true

[export.rename]
"Config" = "mpclipboard_config_t"
"Output" = "mpclipboard_output_t"

[export]
exclude = ["mpclipboard_setup_rustls_on_jvm"]
