name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_command: cargo build --release --target x86_64-unknown-linux-musl --features rustls-platform-verifier
            outputs: target/x86_64-unknown-linux-musl/release/libshared_clipboard_client_generic.a
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo_command: cargo build --release --features rustls-platform-verifier
            outputs: target/release/libshared_clipboard_client_generic.{so,a}
          - os: macos-latest
            target: aarch64-apple-darwin
            cargo_command: cargo build --release --features native-tls
            outputs: target/release/libshared_clipboard_client_generic.{a,dylib}
          - os: ubuntu-latest
            target: aarch64-linux-android
            cargo_command: cargo ndk -t arm64-v8a -o ./target build --release --features rustls-platform-verifier
            outputs: target/arm64-v8a/libshared_clipboard_client_generic.so target/aarch64-linux-android/release/libshared_clipboard_client_generic.a
    steps:
      - uses: actions/checkout@v4

      - name: setup musl
        run: sudo apt update && sudo apt install musl musl-dev
        if: matrix.target == 'x86_64-unknown-linux-musl'

      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-ndk
        if: matrix.target == 'aarch64-linux-android'
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r27c
        if: matrix.target == 'aarch64-linux-android'
      - run: echo "ANDROID_NDK_HOME=${{ steps.setup-ndk.outputs.ndk-path }}" >> $GITHUB_ENV
        if: matrix.target == 'aarch64-linux-android'

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: ${{ matrix.cargo_command }}

      - run: mkdir -p artifacts/shared-clipboard-generic-client
      - run: cp ${{ matrix.outputs }} artifacts/shared-clipboard-generic-client
      - run: cd artifacts && tar czvf ${{ matrix.target }}.tar.gz shared-clipboard-generic-client

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: artifacts/${{ matrix.target }}.tar.gz
          if-no-files-found: error

  build-rustls-platform-verifier-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check
      - run: ./scripts/pack-rustls-platform-verifier-android.sh
      - uses: actions/upload-artifact@v4
        with:
          name: rustls-platform-verifier-android
          path: artifacts/rustls-platform-verifier-android.tar.gz
          if-no-files-found: error

  create-release:
    needs:
      - build
      - build-rustls-platform-verifier-android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: find artifacts

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: "artifacts/**/*.tar.gz,shared-clipboard-client-generic.h"
          token: ${{ secrets.GITHUB_TOKEN }}
