name: release

on:
  push:
    branches: [ master ]

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.target }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cargo_args: "--target x86_64-unknown-linux-musl --features rustls-webpki-roots"
            outputs: target/x86_64-unknown-linux-musl/release/libshared_clipboard_client_generic.a
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            cargo_args: "--features rustls-webpki-roots"
            outputs: target/release/libshared_clipboard_client_generic.{so,a}
          - os: macos-latest
            target: aarch64-apple-darwin
            cargo_args: "--features native-tls"
            outputs: target/release/libshared_clipboard_client_generic.{a,dylib}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - name: setup musl
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: sudo apt update && sudo apt install musl musl-dev
      - run: cargo build --release ${{ matrix.cargo_args }}

      - run: mkdir -p artifacts/shared-clipboard-generic-client
      - run: cp ${{ matrix.outputs }} artifacts/shared-clipboard-generic-client
      - run: cd artifacts && tar czvf ${{ matrix.target }}.tar.gz shared-clipboard-generic-client

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target }}
          path: artifacts/${{ matrix.target }}.tar.gz
          if-no-files-found: error

  create-release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - run: find artifacts

      - name: release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          removeArtifacts: true
          tag: latest
          artifacts: "artifacts/**/*.tar.gz,shared-clipboard-client-generic.h"
          token: ${{ secrets.GITHUB_TOKEN }}
